### ISSUE TITLE
DCD Header

### ISSUE THREAD

**Issue by bondrewd** [Mjolnir-MD/Mjolnir#289]
Currently, when creating a DCD file, Mjolnir writes in the fourth byte of the first block the number 0:

00 - 04  --> 84          // Block size
05 - 08  --> "CORD" // Specifier
09 - 12  --> number  // Number of frames
13 - 16  --> 0            // Previous steps if this is a continuation from another trajectory, currently is just 0
17 - 20  --> 0            // Number of steps between saves, currently is just 0
.
.
.
81 - 84  --> 24         // CHARMM version

Since version 24 is specified, when analyzing trajectories with other libraries like MDAnalysis, it fails to load because it tries to guess the "current time", but the number of "time steps between saves" (bytes 17 to 20) is 0. One solution would be to edit manually the output binary file (joke 😋). The other solution could be just passing this information when initializing the DCDObserver.

Currently, the constructor virtual function has the following signature:

```c++
// open files, write header and so on.                                       
virtual void initialize(const std::size_t total_step, const real_type dt, const system_type&, const forcefield_type&) = 0;
```

We could pass an extra argument, ```save_step_```, by modifying the signature, but this use case is only relevant to DCD files. What could be the best way to pass this value to the DCDObserver without changing the base clase signature? I don't know which feature of c++ is the right one for this use case... 😞

**Comment by ToruNiina** [comment]
Ah okay, I didn't know that because I don't use MDAnalysis.

Since dcd is a file format defined in other place and we are just a user, it is better to conform it as long as possible. I think there is no other way, I will add an argument.

**Comment by ToruNiina** [comment]
Now, in the `develop` branch, dcd file header has a correct `save_interval`. This will be released in the next version.
